stages:
  - test

test:
  image: dbogatov/docker-sources:node--14.4-alpine3.12
  stage: test
  script:
    - npm install
    - npm run coverage
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  tags:
    - docker
